object BuildDependenciesVersions {
    // app level
    const val GRADLE = "7.0.3"
    const val GOOGLE_SERVICES = "4.3.8"
    const val NAVIGATION_PLUGIN = "2.3.5"
    const val KTLINT = "0.41.0"

    const val KOTLIN = "1.5.30"
    const val NAVIGATION = "2.3.5"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val FIREBASE = "28.2.0"
    const val KOIN = "3.0.2"
    const val OKHTTP = "4.9.1"
    const val RETROFIT = "2.9.0"
    const val MOSHI = "1.12.0"
    const val SECURITY_CRYPTO = "1.1.0-alpha03"
    const val TIMBER = "4.7.1"
    const val LIGHT_SPEED = "0.0.52"
    const val LIFECYCLE = "2.4.0-alpha02"
    const val MATERIAL = "1.5.0-alpha04"
    const val LIFECYCLE_EXTENSION = "2.2.0"
    const val APPCOMPAT = "1.3.0"
    const val COROUTINES = "1.5.0"
    const val CORE_KTX = "1.6.0"
    const val COIL = "1.1.1"
    const val PAGING = "3.0.1"

    const val JUNIT = "4.13.2"
    const val ANDROIDX_JUNIT = "1.1.3"
    const val ESPRESSO = "3.4.0"
    const val MOCKK = "1.10.2"
    const val ASSERTJ = "3.17.2"
    const val COROUTINES_TEST = "1.3.9"
    const val JUPITER = "5.7.0"

    const val LEAKCANARY = "2.5"
}
